"use client"

import React, { useState } from 'react'
import { AppLayout } from '@/components/layout/AppLayout'
import { UploadCloud, Scissors, Wand2, Download, CheckCircle2, PlayCircle, Loader2 } from 'lucide-react'

export default function EdicaoPage() {
  const [file, setFile] = useState<File | null>(null)
  const [isProcessing, setIsProcessing] = useState(false)
  const [isDone, setIsDone] = useState(false)

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      setFile(e.dataTransfer.files[0])
      setIsDone(false)
    }
  }

  const handleProcess = () => {
    if (!file) return
    setIsProcessing(true)
    
    // Simula o processamento do vídeo (remoção da marca)
    setTimeout(() => {
      setIsProcessing(false)
      setIsDone(true)
    }, 3000)
  }

  return (
    <AppLayout>
      <div className="flex flex-col h-full max-w-5xl mx-auto gap-8">
        
        {/* HEADER */}
        <div className="shrink-0">
          <h1 className="text-3xl font-bold text-white tracking-tight flex items-center gap-3">
            <Scissors className="text-indigo-400" size={32} />
            Estúdio de Edição (Remoção IA)
          </h1>
          <p className="text-gray-400 mt-2">Remova a marca d'água do Gemini/Veo3 automaticamente com um clique.</p>
        </div>

        {/* WORKSPACE */}
        <div className="flex-1 grid grid-cols-1 lg:grid-cols-2 gap-8">
          
          {/* UPLOAD & PREVIEW */}
          <div className="flex flex-col gap-4">
            <h2 className="text-lg font-semibold text-white">Vídeo Original</h2>
            
            {!file ? (
              <div 
                onDragOver={(e) => e.preventDefault()}
                onDrop={handleDrop}
                className="flex-1 min-h-[400px] border-2 border-dashed border-white/10 hover:border-indigo-500/50 bg-black/20 hover:bg-indigo-500/5 rounded-2xl flex flex-col items-center justify-center text-center p-8 transition-all cursor-pointer group"
              >
                <div className="w-16 h-16 bg-white/5 rounded-full flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                  <UploadCloud size={32} className="text-indigo-400" />
                </div>
                <h3 className="text-xl font-bold text-white mb-2">Arraste o vídeo gerado aqui</h3>
                <p className="text-gray-400 text-sm">Suporta MP4, MOV. (Máx: 50MB)</p>
                <button className="mt-6 px-6 py-2.5 bg-white/10 hover:bg-white/20 text-white rounded-lg font-medium transition-colors">
                  Procurar Arquivo
                </button>
              </div>
            ) : (
              <div className="flex-1 min-h-[400px] bg-black border border-white/10 rounded-2xl relative overflow-hidden flex items-center justify-center group">
                {/* Simulação do Player Original com a marca d'água */}
                <div className="w-full h-full bg-gradient-to-br from-gray-800 to-gray-900 flex items-center justify-center relative">
                  <PlayCircle size={64} className="text-white/30 group-hover:text-white/50 transition-colors cursor-pointer" />
                  
                  {/* Marca d'água simulada */}
                  <div className="absolute bottom-4 right-4 bg-black/60 backdrop-blur-md px-3 py-1.5 rounded flex items-center gap-2 border border-white/10">
                    <span className="text-xs font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">
                      Generated by Gemini
                    </span>
                  </div>
                </div>
                
                <button 
                  onClick={() => { setFile(null); setIsDone(false); }}
                  className="absolute top-4 right-4 px-3 py-1 bg-black/50 hover:bg-black/80 text-xs text-white rounded-md transition-colors"
                >
                  Trocar Vídeo
                </button>
              </div>
            )}
          </div>

          {/* ACTIONS & RESULT */}
          <div className="flex flex-col gap-4">
            <h2 className="text-lg font-semibold text-white">Processamento</h2>
            
            <div className="glass-card p-6 rounded-2xl flex flex-col gap-6">
              
              {/* Settings */}
              <div className="space-y-4">
                <div className="flex flex-col gap-2">
                  <label className="text-sm font-medium text-gray-300">Método de Remoção</label>
                  <div className="grid grid-cols-2 gap-3">
                    <button className="px-4 py-3 bg-indigo-600/20 border border-indigo-500 text-white rounded-lg flex items-center justify-center gap-2 text-sm font-medium">
                      <Scissors size={16} /> Crop (Cortar Borda)
                    </button>
                    <button className="px-4 py-3 bg-white/5 border border-white/10 hover:bg-white/10 text-gray-400 hover:text-white rounded-lg flex items-center justify-center gap-2 text-sm font-medium transition-colors">
                      <Wand2 size={16} /> Blur (Borrar Marca)
                    </button>
                  </div>
                </div>
              </div>

              {/* Action Button */}
              <button 
                onClick={handleProcess}
                disabled={!file || isProcessing || isDone}
                className={`w-full py-4 rounded-xl flex items-center justify-center gap-3 font-bold text-lg transition-all shadow-lg ${
                  !file 
                    ? 'bg-white/5 text-gray-500 cursor-not-allowed' 
                    : isProcessing
                    ? 'bg-indigo-600/50 text-white cursor-wait'
                    : isDone
                    ? 'bg-green-600 text-white'
                    : 'bg-indigo-600 hover:bg-indigo-500 text-white hover:shadow-indigo-500/25'
                }`}
              >
                {isProcessing ? (
                  <>
                    <Loader2 size={24} className="animate-spin" />
                    Processando...
                  </>
                ) : isDone ? (
                  <>
                    <CheckCircle2 size={24} />
                    Marca Removida!
                  </>
                ) : (
                  <>
                    <Wand2 size={24} />
                    Remover Marca d'Água
                  </>
                )}
              </button>

              {/* Result Area */}
              <div className={`mt-4 pt-6 border-t border-white/10 flex flex-col items-center justify-center gap-4 transition-opacity duration-500 ${isDone ? 'opacity-100' : 'opacity-30 pointer-events-none'}`}>
                <div className="w-full aspect-[9/16] max-h-[250px] bg-black rounded-xl border border-green-500/30 overflow-hidden relative group flex items-center justify-center">
                  <div className="w-full h-full bg-gradient-to-br from-gray-800 to-gray-900 flex items-center justify-center">
                     <PlayCircle size={48} className="text-white/30" />
                     {/* Sem marca d'água */}
                  </div>
                  <div className="absolute inset-0 bg-green-500/10 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center backdrop-blur-sm">
                    <button className="px-6 py-3 bg-green-500 hover:bg-green-400 text-white rounded-full font-bold flex items-center gap-2 shadow-lg shadow-green-500/25 transition-all hover:scale-105">
                      <Download size={20} />
                      Baixar MP4 Limpo
                    </button>
                  </div>
                </div>
                <p className="text-sm text-green-400 font-medium">Vídeo pronto para o TikTok!</p>
              </div>

            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  )
}
